# MasterGuardianScanner.ps1
# Finds all Git repos on system and checks for push issues
# Runs autonomously every hour (or on demand)

$ScanLog = "MASTER-SCAN-LOG.txt"
$ProjectsDatabase = "PROJECTS-DATABASE.json"
$LastScanFile = "LAST-SCAN-TIME.txt"

function Write-ScanLog {
    param($Message, $Color = "Gray")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogEntry = "[$Timestamp] $Message"
    Add-Content -Path $ScanLog -Value $LogEntry
    Write-Host $LogEntry -ForegroundColor $Color
}

function Find-AllGitRepos {
    Write-ScanLog "🔍 Scanning for Git repositories..." -Color Cyan
    $allRepos = @()
    
    # Common paths where Git repos live
    $searchPaths = @(
        "$env:USERPROFILE\Documents",
        "$env:USERPROFILE\Desktop", 
        "$env:USERPROFILE\source",
        "$env:USERPROFILE\repos",
        "C:\Users",
        "C:\Projects"
    )
    
    foreach ($searchPath in $searchPaths) {
        if (Test-Path $searchPath) {
            Write-ScanLog "  Scanning $searchPath" -Color Gray
            try {
                $repos = Get-ChildItem -Path $searchPath -Directory -Recurse -ErrorAction SilentlyContinue | 
                    Where-Object { Test-Path "$($_.FullName)\.git" }
                $allRepos += $repos
            } catch {
                # Skip inaccessible folders
            }
        }
    }
    
    # Also check current directory and parent
    $currentDir = Get-Location
    if (Test-Path "$currentDir\.git") {
        $allRepos += Get-Item $currentDir
    }
    
    $allRepos = $allRepos | Select-Object -Unique
    Write-ScanLog "✅ Found $($allRepos.Count) Git repositories" -Color Green
    return $allRepos
}

function Test-GitRepoHealth {
    param($RepoPath)
    
    $issues = @()
    $currentLocation = Get-Location
    
    try {
        Set-Location $RepoPath -ErrorAction Stop
        
        # Test 1: Remote configured?
        $remote = git remote -v 2>$null
        if (-not $remote) {
            $issues += "No remote configured"
        }
        
        # Test 2: Pending commits?
        $pending = git log origin/main..main --oneline 2>$null
        if ($pending) {
            $commitCount = ($pending | Measure-Object).Count
            $issues += "$commitCount pending commits"
        }
        
        # Test 3: Last push status
        $lastPush = git log origin/main -1 --format="%ad" 2>$null
        if (-not $lastPush) {
            $issues += "Never pushed successfully"
        }
        
        # Test 4: Large files in staging
        $largeFiles = git diff --cached --name-only 2>$null | Where-Object { 
            $filePath = Join-Path $RepoPath $_
            if (Test-Path $filePath) {
                (Get-Item $filePath -ErrorAction SilentlyContinue).Length -gt 50MB
            } else { $false }
        }
        if ($largeFiles -and $largeFiles.Count -gt 0) {
            $issues += "Large files detected"
        }
        
    } catch {
        $issues += "Error accessing repository"
    }
    
    Set-Location $currentLocation
    return $issues
}

function Generate-CustomGuardian {
    param($RepoPath, $ProjectName, $Issues)
    
    $issuesText = ($Issues -join ", ") -replace "'", "''"
    $repoPathEscaped = $RepoPath -replace "\\", "\\"
    
    $guardianScript = @"
# Custom Git Guardian for $ProjectName
# Generated by Master Scanner on $(Get-Date)
# Detected issues: $issuesText

`$RepoPath = "$repoPathEscaped"

Write-Host "🛡️ Custom Guardian for $ProjectName starting..." -ForegroundColor Cyan

function Test-Connection {
    try {
        `$null = Invoke-WebRequest -Uri "https://github.com" -TimeoutSec 5 -UseBasicParsing
        return `$true
    } catch {
        return `$false
    }
}

function Try-Push {
    Push-Location `$RepoPath
    `$result = git push origin main 2>&1
    `$success = (`$LASTEXITCODE -eq 0)
    Pop-Location
    return `$success
}

while (`$true) {
    if (Test-Connection) {
        if (Try-Push) {
            Write-Host "✅ Push successful for $ProjectName" -ForegroundColor Green
        } else {
            Write-Host "⚠️ Push failed for $ProjectName - retrying in 5 min" -ForegroundColor Yellow
        }
    }
    Start-Sleep -Seconds 300
}
"@
    
    $guardianPath = Join-Path $RepoPath "CustomGuardian.ps1"
    $guardianScript | Out-File -FilePath $guardianPath -Encoding utf8 -Force
    return $guardianPath
}

function Start-GuardianForProject {
    param($RepoPath, $ProjectName)
    
    $guardianPath = Join-Path $RepoPath "CustomGuardian.ps1"
    if (Test-Path $guardianPath) {
        # Check if already running
        $existing = Get-Process -Name "powershell" -ErrorAction SilentlyContinue | Where-Object {
            $_.CommandLine -like "*$ProjectName*"
        }
        if (-not $existing) {
            Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-File `"$guardianPath`""
            Write-ScanLog "  🛡️ Guardian started for $ProjectName" -Color Green
        }
    }
}

function Update-ProjectDatabase {
    param($AllProjects)
    $AllProjects | ConvertTo-Json -Depth 10 | Out-File -FilePath $ProjectsDatabase -Encoding utf8 -Force
}

# Main execution
Write-ScanLog "🚀 Master Guardian Scanner started" -Color Magenta

$repos = Find-AllGitRepos
$allProjects = @()

foreach ($repo in $repos) {
    Write-ScanLog "Analyzing: $($repo.FullName)" -Color Yellow
    $issues = Test-GitRepoHealth -RepoPath $repo.FullName
    
    $project = @{
        Name = $repo.Name
        Path = $repo.FullName
        Issues = $issues
        Status = if ($issues.Count -eq 0) { "Healthy" } else { "Needs Attention" }
        Color = if ($issues.Count -eq 0) { "#00cc66" } else { "#ffcc00" }
        LastChecked = (Get-Date).ToString()
    }
    
    if ($issues.Count -gt 0) {
        Write-ScanLog "  ⚠️ Issues found: $($issues -join ', ')" -Color Yellow
        $guardianPath = Generate-CustomGuardian -RepoPath $repo.FullName -ProjectName $repo.Name -Issues $issues
        Write-ScanLog "  ✅ Custom Guardian created at: $guardianPath" -Color Green
        Start-GuardianForProject -RepoPath $repo.FullName -ProjectName $repo.Name
    } else {
        Write-ScanLog "  ✅ Repository is healthy" -Color Green
    }
    
    $allProjects += $project
}

Update-ProjectDatabase -AllProjects $allProjects

# Record scan time
Get-Date | Out-File -FilePath $LastScanFile -Force

Write-ScanLog "✅ Scan complete. Found $($allProjects.Count) projects." -Color Green
Write-ScanLog "🛡️ Guardians active for projects with issues." -Color Magenta

# Output summary for dashboard
$summary = $allProjects | Select-Object Name, Status, Issues | ConvertTo-Json
Write-ScanLog "SUMMARY: $summary" -Color Gray
