services:
  - type: web
    name: node00-omega
    runtime: static
    repo: https://github.com/MayaAngels/NODE00
    branch: main
    buildCommand: ""
    staticPublishPath: ./
    indexDocument: index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
